image: registry.suse.com/bci/bci-base:latest

stages:
  - check_version
  - build_catalog

variables:
  REGISTRY: $CI_REGISTRY
  REGISTRY_USER: $CI_REGISTRY_USER
  REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
  IMAGE_NAMESPACE: $CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME

include:
  - '/stages/extension-catalog.ci.yml'
