export const PRODUCT_NAME = 'Internal Developer Portal';
export const PRODUCT_ROUTE_NAME = 'idp';
export const BLANK_CLUSTER = '_';
export const CUSTOM_K8S_RESOURCE_NAME = 'trident';
export const TRIDENT_PAGE_NAME = 'Trident';
export const DEV_TOOLS_PAGE_NAME = 'DevTools';
export const WIKI_PAGE_NAME = 'Wiki';
export const HOME = 'home';
export const WISH_PAGE_NAME = 'Wish';